const ItemMaster =`CREATE TABLE IF NOT EXISTS ItemMaster (
    ItemId BIGINT PRIMARY KEY NOT NULL,
    RelativeNo BIGINT NOT NULL,
    ItemName NVARCHAR(1000),
    Region NVARCHAR(200),
    ItemType CHAR(10) NOT NULL,
    CategoryId INT,
    MaterialCode VARCHAR(50),
    VendorId BIGINT,
    LoationId BIGINT,
    ReOrderLevel INT,
    UnitPrice NUMERIC(18, 4),
    BatchCode VARCHAR(50),
    UnitPrice1 NUMERIC(18, 4),
    UnitPrice2 NUMERIC(18, 4),
    PartNo VARCHAR(50),
    Color VARCHAR(50),
    Packing VARCHAR(50),
    Weight VARCHAR(50),
    Shape VARCHAR(50),
    ItemSize VARCHAR(10000),
    Ref1 VARCHAR(50),
    Ref2 VARCHAR(50),
    StockType BIT,
    UnitId BIGINT,
    ExpenseACC VARCHAR(40),
    Image LONGBLOB,
    Active BIT,
    LastPurPrice NUMERIC(18, 4),
    Services BIT,
    AssetACC VARCHAR(40),
    SupCode VARCHAR(50),
    Barcode VARCHAR(50),
    AliasName VARCHAR(50),
    UserId BIGINT,
    GroupDebitAcc VARCHAR(20),
    GroupCreditAcc VARCHAR(20),
    LandingCost FLOAT,
    BaseValue FLOAT,
    RackID BIGINT,
    status BIT,
    Type VARCHAR(50),
    Height_N FLOAT,
    Width_N FLOAT,
    CurStock FLOAT,
    Type_ID BIGINT,
    Model_ID BIGINT,
    TaxID INT,
    Show_hide BIT,
    showSalesman BIT,
    ReorderCheck BIT,
    deflocationname VARCHAR(50),
    deflocation INT,
    CountryId INT,
    Redm_rewardPoint NUMERIC(18, 2),
    VAT BIGINT,
    VATPERC NUMERIC(18, 2),
    Vat_Inclus BIT,
    PackageID VARCHAR(50),
    GenericName VARCHAR(500),
    ManufName VARCHAR(500),
    MinimumQty BIGINT,
    SupplierName VARCHAR(500),
    c_PromoCode NVARCHAR(50),
    ISserialNo BIT,
    isAddi_Barcode BIT,
    AddDesc NVARCHAR(800),
    Is_Subscription BIT,
    IswaingScale BIT,
    Percantage DECIMAL(18, 2),
    NoofDays INT,
    WarrantyType NVARCHAR(30),
    IsWarranty BIT,
    StationCode INT,
    isbatchWise BIT,
    Opening_Acc VARCHAR(50),
    BatchNumber VARCHAR(50),
    Opening_SeriesNo VARCHAR(50),
    Opening_Qty INT,
    Opening_Rate DECIMAL(18, 3),
    JV_No VARCHAR(50),
    LocId INT,
    Add_PartNo VARCHAR(60),
    BOMNO INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;




module.exports = ItemMaster