const createAccounts=`CREATE TABLE IF NOT EXISTS AccountsTransactions (
    transsno BIGINT AUTO_INCREMENT PRIMARY KEY,
    accno NVARCHAR(50) NOT NULL,
    CompanyId VARCHAR(20) NOT NULL,
    transdate DATETIME NOT NULL,
    particulars NVARCHAR(1000),
    debit NUMERIC(18, 4) NOT NULL,
    credit NUMERIC(18, 4) NOT NULL,
    fcdebit NUMERIC(18, 4),
    fccredit NUMERIC(18, 4),
    vouchertype VARCHAR(25) NOT NULL,
    voucherno VARCHAR(50),
    user_id BIGINT NOT NULL,
    status VARCHAR(25),
    description NVARCHAR(2000),
    tstamp DATETIME NOT NULL,
    refno CHAR(50),
    fsno NUMERIC(18, 0) NOT NULL,
    allocdebit NUMERIC(18, 4),
    alloccredit NUMERIC(18, 4),
    allocbalance NUMERIC(18, 4),
    fcallocdebit NUMERIC(18, 4),
    fcalloccredit NUMERIC(18, 4),
    fcallocbalance NUMERIC(18, 4),
    location INT,
    jobno BIGINT,
    costcenter_id BIGINT,
    approvaldt DATETIME,
    department INT,
    fcrate NUMERIC(18, 4),
    currencyid INT,
    drgram FLOAT,
    crgram FLOAT,
    cheqno VARCHAR(50),
    lpono VARCHAR(50),
    cheqdate DATETIME,
    opposentrydesc VARCHAR(2000),
    allocupdatebal FLOAT,
    deptid BIGINT,
    vatno NVARCHAR(50),
    retailcrdr BIT,
    vatableamount DECIMAL(18, 4),
    duedate DATETIME,
    transtype NVARCHAR(50),
    isapproval BIT,
    agent_id INT,
    payrollid VARCHAR(50),
    pay_transdate DATETIME,
    breakup_id INT,
    cheqbankname NVARCHAR(130),
    cheqbankaccno NVARCHAR(30),
    salesmanid INT,
    unitid INT,
    propertyid INT,
    stationcode INT,
    instrumenttype NVARCHAR(20),
    oppsitaccno VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`;
  

 module.exports=createAccounts