const createMaster=`CREATE TABLE IF NOT EXISTS masteraccounts  (
    id INT,
    sno INT PRIMARY KEY AUTO_INCREMENT,
    relativeno NVARCHAR(40) NOT NULL,
    accno NVARCHAR(40) NOT NULL,
    accname NVARCHAR(80) NOT NULL,
    acctype CHAR(20) NOT NULL,
    mainhead NVARCHAR(50) NOT NULL,
    subhead NVARCHAR(50) NOT NULL,
    imagekey NVARCHAR(50) NOT NULL,
    fsno NUMERIC(18, 0) NOT NULL,
    systemacc CHAR(20) NOT NULL,
    status CHAR(10),
    userid BIGINT,
    dtcreate DATETIME,
    currencyid NUMERIC(18, 0),
    gpacc CHAR(10),
    acacc CHAR(10),
    edacc CHAR(10),
    openbalance NUMERIC(18, 4),
    totaldebit NUMERIC(18, 4),
    totalcredit NUMERIC(18, 4),
    manualcode NVARCHAR(50),
    costcenterid BIGINT,
    showsumintb BIT,
    assetvalue FLOAT,
    assetdepvalue FLOAT,
    assetqty FLOAT,
    lifeinyrs FLOAT,
    assetdepmode VARCHAR(50),
    assetdate DATETIME,
    isasset BIT,
    costcentersub BIT,
    sortno INT,
    isairacc BIT,
    isseaacc BIT,
    ispayhead INT,
    openbalcr DECIMAL(18, 3),
    close_cr DECIMAL(18, 3),
    crdr NVARCHAR(5),
    openingvalue FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`;
  

  module.exports = createMaster;